replicaCount: 3

image:
  repository: kong/httpbin
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  name: "httpbin"

service:
  type: ClusterIP
  port: 8000

container:
  port: 80
