name: Patch

on:
  workflow_dispatch:

jobs:
  default:
    name: "Patch"
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Merge manifest"
        run: |
          gh pr merge chore/charts --auto --squash
