name: Release

on:
  push:
    branches:
      - main

jobs:
  default:
    name: "Release"
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Configure git"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

      - name: "Install helm"
        uses: azure/setup-helm@v3

      - name: "Create release"
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_SKIP_EXISTING: true
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
