name: Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1

      - name: Create cluster
        uses: helm/kind-action@v1.5.0

      - name: Install cert-manager
        run: helm install cert-manager

      - name: Run chart-testing
        run: ct install --chart-dirs . --charts .
        working-directory: charts/cluster-api-operator

      - name: Uninstall cert-manager
        run: helm uninstall cert-manager
