name: Test

on:
  pull_request:

jobs:
  default:
    name: "Tests"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Install helm"
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: "Install python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: "Setup tests"
        uses: helm/chart-testing-action@v2.6.1

      - name: "Create cluster"
        uses: helm/kind-action@v1.8.0

      - name: "Lint charts"
        run: ct lint --all

      - name: "Install charts"
        run: ct install --all
