name: Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  default:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install helm"
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: "Install python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: "Setup tests"
        uses: helm/chart-testing-action@v2.3.1

      - name: "Create cluster"
        uses: helm/kind-action@v1.5.0

      - name: "Install dependencies"
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --version v1.11.0 --set installCRDs=true

      - name: "Run tests"
        run: ct install --chart-dirs . --charts .
        working-directory: charts/cluster-api-operator

      - name: "Uninstall dependencies"
        run: |
          helm --namespace cert-manager delete cert-manager
