name: Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  default:
    name: "Update"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Download manifest"
        run: |
          wget -O charts/cluster-api-operator/templates/operator.yaml \
            https://github.com/kubernetes-sigs/cluster-api-operator/releases/latest/download/operator-components.yaml

      - name: "Configure git"
        run: |
          git config user.name "GitHub Actions"
          git config user.email "action@github.com"

      - name: "Merge manifest"
        id: merge
        run: |
          if [ -n "$(git status charts/ --porcelain)" ]; then
            git checkout -b chore/charts
            git add charts/
            git commit -m "chore(update): replace operator manifest"
            git push origin chore/charts
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/ljtill/helm-cluster-api/pulls \
              -f title="chore(update): replace operator manifest" \
              -f body="" \
              -f head="chore/charts" \
              -f base="main"
            echo "PULL_REQUEST=true" >> $GITHUB_OUTPUT
          else
            echo "PULL_REQUEST=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: "Enable auto-merge"
        run: |
          gh pr merge chore/charts --auto --squash
        if: steps.merge.outputs.PULL_REQUEST == "true"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
